#pragma once

/* RGBLIGHT configuration */
#define WS2812_DI_PIN A9
#define RGBLIGHT_LED_COUNT 2
#define RGBLIGHT_LED_MAP { 1, 0 }
#define RGBLED_SPLIT { 1, 1 }
#define RGBLIGHT_LAYERS
#define RGBLIGHT_MAX_LAYERS 9
// #define RGBLIGHT_EFFECT_CHRISTMAS
// #define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_STATIC_LIGHT
// #define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_SLEEP
#define RGBLIGHT_DEFAULT_HUE 0
#define RGBLIGHT_DEFAULT_SAT 0
#define RGBLIGHT_DEFAULT_VAL 0
#define RGBLIGHT_LIMIT_VAL 140

#define USB_VBUS_PIN A10

#undef  SPLIT_USB_DETECT
